# Generated by Django 5.0.2 on 2024-02-15 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfa', '0002_feedback_courses_content_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_or_phone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='thumbnail',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='content_thumbnail'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='course_banner',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='course_banner_pics'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='course_picture',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='course_pics'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='profile_pics'),
        ),
    ]
